[package]
name = "wasm-convert"
version = "0.0.0-local"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
convert = { path = "../convert-crate" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.69"
