name: Release, publish and update

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup dependencies and cache
        uses: ./.github/actions/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup release dependencies
        uses: ./.github/actions/prepare-release

      - name: Setup github package registry credentials
        run: echo 'registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=$NPM_TOKEN' > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install node dependencies
        run: yarn install

      - name: Semantic release
        run: yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

      - name: Setup github package registry credentials
        run: echo 'registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=$GHP_TOKEN' > ~/.npmrc
        env:
          GHP_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Publish to github package
        run: npm publish
        working-directory: ./wasm-package 
