name: Release, publish and update

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Release kind'
        options:
          - patch
          - minor
          - major
        required: true
        type: choice
      releaseChangelog:
        description: 'Changelog'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Bump versions
        run: bash ./scripts/bumps.sh "$KIND"
        env:
          KIND: "{{ inputs.releaseKind }}"
      - name: "Setup dependencies and cache"
        uses: ./.github/actions/setup
      - name: "Setup release dependencies"
        uses: ./.github/actions/setup
      - name: Get package versions
        id: version
        run: |
          VERSION=$(toml get -r ./caido-convert/Cargo.toml package.version)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        
      - name: Create a new tag 
        run: git tag -a "v$VERSION" -m "Release v$VERSION"
        env:
          CHANGELOG: "{{ inputs.releaseChangelog }}"
